"""First migration

Revision ID: 4c75da36adbe
Revises: 
Create Date: 2019-04-24 17:15:02.535162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c75da36adbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_photos', sa.Column('pic_id', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_photos', 'pic_id')
    # ### end Alembic commands ###
