"""First migration

Revision ID: a50cb752425e
Revises: 4c75da36adbe
Create Date: 2019-04-24 17:26:44.433425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50cb752425e'
down_revision = '4c75da36adbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pic_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pic_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profile_photos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profile_photos_pkey')
    )
    # ### end Alembic commands ###
